feat: GameInfo Worker 추가
TeamTailHead/TailHeadClient pull request #2
Opened 2022-10-26 10:51 UTC by H0ngJun

만들어놓고index.tsx에 추가를 안한거 같아요...

2022-10-27 02:14 UTC, Tekiter requested changes
일단 이거 수정해줘!

2022-10-27 02:14 UTC, Tekiter commented on src/states/game.ts
> +});
```suggestion
export const historyWordAtom = atom<string[]>({
  key: "historyWord",
  default: [],
});
```

2022-10-27 02:22 UTC, H0ngJun commented on src/states/game.ts
> +});
넵 알겠습니닷!

2022-10-27 06:03 UTC, Tekiter commented
다음부터 수정사항에 대해서 커밋 메시지는 간단하게 언급하고, 자세한 리뷰 변경사항 내용은 코멘트로 달아줘!

2022-10-27 06:07 UTC, Tekiter requested changes

2022-10-27 06:07 UTC, Tekiter commented on src/states/game.ts
> +export const historyWordAtom = atom<string[]>({
하나 또 생각난건데, `wordHistoryAtom` 으로 바꾸는게 더 좋은것 같아!

2022-10-28 00:54 UTC, H0ngJun commented on src/states/game.ts
> +export const historyWordAtom = atom<string[]>({
하잇 바꿔놓겠습니닷

2022-10-28 00:55 UTC, H0ngJun commented
커밋 메시지도 간단하게 달고 코멘트로 세부사항 올리도록 할게욤

2022-10-28 03:31 UTC, H0ngJun commented
센세 GameInfoWorker에서 wordHistory를 어떻게 사용해야할지를 모르겠습니다 ㅠㅠ에러가 나네요 gameTurnInfo에 wordhistory를 선언해놓지 않아서 에러가 나는 것은 이해했으나 그러면 이것을 어디에 문장으로 추가하여 사용해야할 지 모르겠습니다...

2022-10-28 04:07 UTC, Tekiter commented
> 에러가 나네요
무슨 에러 상황인지 알아야 도와줄 수 있어! (에러 메시지, 코드 예시 등)

보니까 history를 저장하는건 조금 복잡해질 것 같아서 일단 wordHistory를 기록하는건 없이 진행해줘!

2022-10-28 04:17 UTC, H0ngJun commented
아하 담부터는 어떤 오류인지 정확하게 명시하도록 하겠슴다! 이번 오류는 이제 어디에 이걸 추가해도 밑에 빨간 줄이 떠서 이 오류를 말한거였습니당~헣...일단 선언만 해놓고 진행할게요~

2022-11-03 11:21 UTC, Tekiter approved these changes
LGTM!

2022-11-03 11:21 UTC, merged