InGamePlayerList 관련 작업
TeamTailHead/TailHeadClient pull request #7
Opened 2022-11-04 03:16 UTC by H0ngJun

InGamePlayerList와 InGamePlayerListITem만 일단 완성 시켰는데 InGameScreen에서 사용해서 만들기 전에 확인 받으려고 올려봅니닷
이거 하면서 이전에 만든 game.ts랑 GameInfoWorker도 조금 수정해했습니당 사용하려고 하니까 score관련해서 따로 안만들었더라구요 헣헣
*그리고 질문사항입니다!*
1. 질문 사항 currentPlayer관련해서 InGamePlayerListItem에서 처리하는 방식이 맞는지(18번줄)
2. currentPlayer관련해서 states에서 currentPlayer에서도 선언되어 있고, game.ts에서도 선언되어 있어여 ㅠ우짤까요?

2022-11-04 03:43 UTC, Tekiter requested changes
currentPlayer.ts 의 currentPlayerAtom은 현재 접속한 나 자신의 정보를 담고 있고, game.ts 의 currentPlayerIdAtom 은 게임에서 누구의 턴인지 정보를 담고 있어서 둘이 달라! 혼동의 여지가 있으니 currentPlayerIdAtom 을 다른 이름으로 바꿔주는게 좋을 것 같아. 

한가지 생각나는건 thisTurnPlayerId 인데, 한번 고민해봐!

2022-11-04 03:43 UTC, Tekiter commented on src/components/ingame/InGameScreen.tsx
> +      <StartButton onClick={handleGameStart}>게임 시작!</StartButton>
복사했지만 사용하지 않는 로직은 빼줘!

2022-11-04 04:25 UTC, H0ngJun commented on src/components/ingame/InGameScreen.tsx
> +      <StartButton onClick={handleGameStart}>게임 시작!</StartButton>
아하 당장 내가 제대로 이해 못하고 혼동하고 있었넼ㅋㅋㅋ넹 currentPlayerIdAtom관련된 것들 다 찾아서 thisTurnPlayerId에 맞춰서 수정하도록 하겠습니닷. screen은 일단 오류 있으면 푸쉬가 안될거같길래 남겨두고 올렸었엉,,,,히히 다음 커밋에는 screen까지 최대한 만들어서 올려볼게요~~

2022-11-12 18:38 UTC, Tekiter requested changes

2022-11-12 18:38 UTC, Tekiter commented on src/components/result/ResultScreen.tsx
> +  };
camel case 해주세용

2022-11-12 18:40 UTC, Tekiter commented
그리고 #10 이랑 이거랑 둘다 `ingame생성` 브랜치를 머지시키는데 뭔가 이상한 것 같아! 한번 확인해줘!

2022-11-14 14:25 UTC, H0ngJun commented on src/components/result/ResultScreen.tsx
> +  };
넹!

2022-11-14 14:27 UTC, H0ngJun commented on src/components/result/ResultScreen.tsx
> +  };
그리고 #10 과 이거랑 둘  ingame생성 이라는 브랜치에서 작업한거라 머지가 똑같은 브랜치에서 일어난 걸로 되었어용,,,,,이걸 우째야할지 모르겠어요 저는 ㅠㅠㅠ너무 하나의 브랜치로만 계속 작업했나봐유 내일 봐주실 수 있으실까용..?

2022-11-14 14:32 UTC, Tekiter commented on src/components/result/ResultScreen.tsx
> +  };
오키오키!

2022-11-15 10:45 UTC, Tekiter approved these changes

2022-11-15 11:22 UTC, merged